---
- name: Configure deployed certmanager (k8s/helm)
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    domain_zone_staging: "{{ lookup('env', 'DOMAIN_ZONE_STAGING') | default('algorisma.com', true) }}"
    domain_zone_prod: "{{ lookup('env', 'DOMAIN_ZONE_PROD') | default('algorisma.com', true) }}"
    cf_token_prod: "{{ lookup('env', 'CF_TOKEN_PROD') }}"
    cf_token_staging: "{{ lookup('env', 'CF_TOKEN_STAGING') }}"
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') | default('../../../k8s-dev.yaml', true) }}"
  tasks:
    - name: Create certificate issuers manifest
      template:
        src: manifests/issuer.yaml.j2
        dest: /tmp/issuer.yaml
        mode: '0644'

    - name: Apply certificate issuers manifest
      ansible.builtin.shell: |
        kubectl apply -f /tmp/issuer.yaml
        
        exit 0
    - name: Create resolver/api manifest
      template:
        src: manifests/resolver_api.yaml.j2
        dest: /tmp/resolver_api.yaml
        mode: '0644'

    - name: Apply resolver/api manifest
      ansible.builtin.shell: |
        kubectl apply -f /tmp/resolver_api.yaml
        
        exit 0    
    - name: Create local certs manifest
      template:
        src: manifests/local_certs.yaml.j2
        dest: /tmp/local_certs.yaml
        mode: '0644'

    - name: Apply local certs manifest
      ansible.builtin.shell: |
        kubectl apply -f /tmp/local_certs.yaml
        
        exit 0