---
apiVersion: v1
kind: Service
metadata:
  name: welcome-nginx
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-nginx
  namespace: production
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.25.2
        name: nginx
        ports:
        - containerPort: 80
---