---
- name: Deploy argocd (k8s)
  hosts: localhost
  become: true
  vars:
  tasks:
    - name: Create Namespace (if doesn't exist)
      ansible.builtin.shell: |
        tmpNamespace="argocd"
        kubectl get namespace | grep -q "^$tmpNamespace " || kubectl create namespace $tmpNamespace

        exit 0
     
    - name: Install manifest
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    
    - name: Patch service to LoadBalancer type
      ansible.builtin.shell: |
        kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
        echo "Installed."

        exit 0
    
    - name: Display default pass for ArgoCD
      ansible.builtin.shell: |
        echo "Default pass for ArgoCD..."
        kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo

        exit 0
    


