---
- name: Deploy certmanager (k8s/helm)
  hosts: localhost
  become: true
  vars:
    domain_zone_staging: "{{ lookup('env', 'DOMAIN_ZONE_STAGING') | default('algorisma.com', true) }}"
    domain_zone_prod: "{{ lookup('env', 'DOMAIN_ZONE_PROD') | default('algorisma.com', true) }}"
    cf_token_prod: "{{ lookup('env', 'CF_TOKEN_PROD') }}"
    cf_token_staging: "{{ lookup('env', 'CF_TOKEN_STAGING') }}"
  gather_facts: true
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') | default('../../k8s-dev.yaml', true) }}"
  tasks:
    - name: Add / Update certmanager helm repo
      ansible.builtin.shell: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

        exit 0
    
    - name: Create Namespace (if doesn't exist)
      ansible.builtin.shell: |
        tmpNamespace="cert-manager" && kubectl get namespace | grep -q "^$tmpNamespace " || kubectl create namespace $tmpNamespace

        exit 0
    - name: Install CRD(s)
      ansible.builtin.shell: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.crds.yaml

        exit 0
    - name: Install/upgrade chart
      ansible.builtin.shell: |
        helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --values=cert-values.yaml --version v1.13.2
        
        exit 0